# Replace this with your API key from mcbouncer.com/apikey
apiKey: REPLACE

numBansDisallow: 10
showBanMessages: true
defaultBanMessage: 'Banned for rule violation.'
defaultKickMessage: 'Kicked by an admin.'

# Download plugins from mcbouncer.com/plugins.  Enter the names of all plugins, case sensitive, in standard YML format.
# EX - 
# plugins:
#   - 'EnhancedKick'
#   - 'MCBansIntegration'
plugins: